FROM tomcat:jre21

RUN rm -rf /usr/local/tomcat/webapps/ROOT

COPY tomcat/tomcat-server.xml /usr/local/tomcat/conf/server.xml
COPY tomcat/tomcat-web.xml /usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml

COPY ./dist/license-gui/browser /usr/local/tomcat/webapps/ROOT



EXPOSE 8080

CMD ["catalina.sh", "run"]
