FROM eclipse-temurin:24

COPY target/*.jar /home/app/license-server.jar

RUN apt update && apt upgrade -y

EXPOSE 8080

CMD cd /home/app/

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /home/app/license-server.jar"]
