FROM alpine
RUN apk add --no-cache curl
CMD ["sh", "-c", "until $(curl --output /dev/null --silent --head --fail http://keycloak:8080/auth/realms/master); do printf '.'; sleep 5; done; echo 'Keycloak is up!'"]
