FROM eclipse-temurin:25

COPY target/*.jar /home/app/license-server.jar

RUN apt update && apt upgrade -y

EXPOSE 8080

WORKDIR /home/app

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /home/app/license-server.jar"]
